#!/bin/sh

echo ""
echo "################################################################"
echo "##                                                            ##"
echo "##           Enabling stable Debian repositories...           ##"
echo "##                                                            ##"
echo "################################################################"
echo ""

sources_list_path="/etc/apt/sources.list"
sudo cp $sources_list_path "$sources_list_path.backup__old"
sudo sed -i 's/^/#/' $sources_list_path

debian_version_codename=(grep "^VERSION_CODENAME=" /etc/os-release | cut -d'=' -f2)
sudo echo "" >> $sources_list_path
sudo echo "# Generated by Sejoslaw's Setup Crostini Script" >> $sources_list_path
sudo echo "deb http://deb.debian.org/debian $debian_version_codename main contrib non-free non-free-firmware" >> $sources_list_path
sudo echo "deb http://deb.debian.org/debian $debian_version_codename-updates main contrib non-free non-free-firmware" >> $sources_list_path
sudo echo "deb http://deb.debian.org/debian-security $debian_version_codename-security main contrib non-free non-free-firmware" >> $sources_list_path

echo ""
echo "################################################################"
echo "##                                                            ##"
echo "##                    Updating Crostini...                    ##"
echo "##                                                            ##"
echo "################################################################"
echo ""

sudo apt update && sudo apt dist-upgrade -y && sudo apt autoremove -y

echo ""
echo "################################################################"
echo "##                                                            ##"
echo "##                   Setting up utilities...                  ##"
echo "##                                                            ##"
echo "################################################################"
echo ""

echo ""
read -p "## Install Google Chrome in Crostini (from official DEB file)? (yes/empty)" _installChrome;

if [ "$_installChrome" != "" ]
then
    file_name=google-chrome-stable_current_amd64.deb

    sudo apt install wget
    wget https://dl.google.com/linux/direct/$file_name
    sudo apt install -y ./$file_name
    sudo rm $file_name
fi

echo ""
read -p "## Install GNOME Boxes (from Debian repository)? (yes/empty)" _installGnomeBoxes;

if [ "$_installGnomeBoxes" != "" ]
then
    sudo apt install gnome-boxes
fi

echo ""
read -p "## Install Steam? (yes/empty)" _installSteam;

if [ "$_installSteam" != "" ]
then
fi

echo ""
read -p "## Install Flatpak? (yes/empty)" _installFlatpak;

if [ "$_installFlatpak" != "" ]
then
    sudo apt install flatpak

    echo "## Adding Flathub repo..."
    flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
fi
